object fFormNormal: TfFormNormal
  Left = 0
  Top = 0
  ClientHeight = 480
  ClientWidth = 320
  Caption = 'title'
  CloseButton.Text = #36820#22238
  CloseButton.UI = 'round'
  CloseButton.IconCls = 'arrow_left'
  CloseButton.DefaultIcon = False
  TitleButtons = <>
  ShowAnimation = 'pop'
  OnTitleButtonClick = UnimFormTitleButtonClick
  PixelsPerInch = 96
  TextHeight = 13
  ScrollPosition = 0
  ScrollHeight = 47
  PlatformData = {}
end
